import { chromium } from 'playwright-core';
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const ctx = await browser.newContext({ viewport: { width: 1400, height: 820 } });
const page = await ctx.newPage();
const errors: string[] = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('http://localhost:8787');
await page.waitForTimeout(600);
await page.click('#screen-menu button:has-text("Private room")');
await page.waitForTimeout(400);
await page.click('#screen-lobby .lobby-actions button:has-text("Add bot")');
await page.click('#screen-lobby button:has-text("Start game")');
await page.waitForTimeout(700);
await page.click('text=Lock in & start');
await page.waitForTimeout(500);
await page.click('.race-card >> text=Wildgrove');
const send = (m: unknown) => page.evaluate((x) => (window as any).winterward.net.send(x), m);
for (const [x, y] of [[9, 10], [9, 14], [12, 9], [12, 13]]) await send({ type: 'cmd', cmd: { c: 'build', tower: 'grove_1', x, y } });
await page.waitForTimeout(800);
const before = await page.evaluate(() => { const s = (window as any).winterward.game.state; return { towers: s.towers.size, gold: s.me.gold, races: s.me.races, url: location.href }; });
console.log('before reload', JSON.stringify(before));
await page.reload();
await page.waitForTimeout(2500);
const after = await page.evaluate(() => { const g = (window as any).winterward.game; if (!g) return 'no game view'; const s = g.state; return { towers: s.towers.size, gold: s.me?.gold, races: s.me?.races, you: s.you, phase: s.wave.phase }; });
console.log('after reload ', JSON.stringify(after));
await page.screenshot({ path: (process.argv[2] ?? 'screenshots') + '/reconnect.png' });
console.log(errors.join('\n'));
await browser.close();
